repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-byte-order-marker
      - id: check-ast
      - id: check-toml
      - id: check-xml-declaration
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        types: [javascript, typescript]
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [javascript, typescript]
      - id: stylelint
        name: stylelint
        entry: npx stylelint --fix
        language: node
        types: [css, scss, less]
      - id: eslint-react
        name: eslint-react
        entry: npx eslint --fix
        language: node
        types: [javascript, typescript, jsx, tsx]
